---
- name: Configure Automation Controller - Credentials Only
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - configs/auth.yml
  vars:
    controller_credentials:
      - name: lab-credentials
        credential_type: Machine
        organization: Default
        inputs:
          username: rhel
          password: ansible123!
          ssh_key_data: "{{ lookup('file', '/home/rhel/.ssh/id_rsa') }}"
  tasks:
    - name: Create credentials
      ansible.builtin.include_role:
        name: infra.aap_configuration.controller_credentials
